
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6  # pick latest stable version
    container_name: keycloak
    command: start-dev   # use start-dev for quick dev, or start for prod
    environment:
      # Admin user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Database config (H2 is built-in for dev, use Postgres for prod)
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  opa:
    image: openpolicyagent/opa:latest
    platform: linux/amd64
    container_name: opa
    command:
      [
        "run",
        "--server",
        "--addr=0.0.0.0:8181",

      ]
    ports:
      - "8181:8181"     # OPA API

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
